# This is the list of sinks
# The api are suspetible to attack if value passed are not properly sanitize.
#
# File format:
# <<<
# [Unique ID of the sink]:
#   namespace: [Namespace where the class is present]
#   className: [Class of the API]
#   member: ["method" => method call or "field" for assignment]
#   name: [Field name (assignment) or Method name (method call)]
#   argTypes: (Optional field) [Parameter types signature]
#   injectableArguments : (Optional field) [Index of the argument for injectable query, starting from the left]
#   passwordArguments : (Optional field) [Index of the argument for password parameter, starting from the left]
#   
#   locale: [Id of a localization in Messages.yml, This value can be reused for multiple sinks]
# <<<

# System.Data

sqlcommand_constructor:
  namespace: System.Data.SqlClient
  className: SqlCommand
  member: method
  name: .ctor
  injectableArguments: 0
  locale: SG0026

sqlcommand_field:
  namespace: System.Data.SqlClient
  className: SqlCommand
  member: field
  name: CommandText
  injectableField: true
  locale: SG0026

dbcommand_field:
  namespace: System.Data.Common
  className: DbCommand
  member: field
  name: CommandText
  injectableField: true
  locale: SG0026

oledbcommand_constructor:
  namespace: System.Data.OleDb
  className: OleDbCommand
  member: method
  name: .ctor
  injectableArguments: 0
  locale: SG0020

oledbdataadapter_constructor:
  namespace: System.Data.OleDb
  className: OleDbDataAdapter
  member: method
  name: .ctor
  injectableArguments: 0
  locale: SG0020

odbccommand_constructor:
  namespace: System.Data.Odbc
  className: OdbcCommand
  member: method
  name: .ctor
  injectableArguments: 0
  locale: SG0025

odbcdataadapter_constructor:
  namespace: System.Data.Odbc
  className: OdbcDataAdapter
  member: method
  name: .ctor
  injectableArguments: 0
  locale: SG0025

# System.Data.Linq

DataContext_ExecuteQuery_0:
  namespace: System.Data.Linq
  className: DataContext
  member: method
  name: ExecuteQuery
  argTypes: (System.String, params System.Object[])
  injectableArguments: 0
  locale: SG0002

DataContext_ExecuteQuery_1:
  namespace: System.Data.Linq
  className: DataContext
  member: method
  name: ExecuteQuery
  argTypes: (System.Type, System.String, params System.Object[])
  injectableArguments: 1
  locale: SG0002

# System.Web.UI.WebControls

sqldatasource_constructor:
  namespace: System.Web.UI.WebControls
  className: SqlDataSource
  member: method
  name: .ctor
  injectableArguments: 0
  locale: SG0014

sqldatasource_field:
  namespace: System.Web.UI.WebControls
  className: SqlDataSource
  member: field
  name: SelectCommand
  injectableField: true
  locale: SG0014

sqldatasourceview_field:
  namespace: System.Web.UI.WebControls
  className: SqlDataSourceView
  member: field
  name: SelectCommand
  injectableField: true
  locale: SG0014

# Microsoft.Whos.Framework.Data

sqlutility_method:
  namespace: Microsoft.Whos.Framework.Data
  className: SqlUtility
  member: method
  name: ExecuteDataset
  injectableArguments: 0
  locale: SG0014

# Process

systemdiagnostic_process:
  namespace: System.Diagnostics
  className: Process
  member: method
  name: Start
  injectableArguments: 0
  locale: SG0001

systemdiagnostic_process_filename:
  namespace: System.Diagnostics
  className: ProcessStartInfo
  member: field
  name: FileName
  injectableField: true
  locale: SG0001

systemdiagnostic_process_arguments:
  namespace: System.Diagnostics
  className: ProcessStartInfo
  member: field
  name: Arguments
  injectableField: true
  locale: SG0001

 #XPath

XmlNode_SelectNodes:
  namespace: System.Xml
  className: XmlNode
  member: method
  name: SelectNodes
  injectableArguments: 0
  locale: SG0003

XmlNode_SelectSingleNode:
  namespace: System.Xml
  className: XmlNode
  member: method
  name: SelectSingleNode
  injectableArguments: 0
  locale: SG0003

#Path traversal

#File API

#Append
File_AppendAllLines:
  namespace: System.IO
  className: File
  member: method
  name: AppendAllLines
  injectableArguments: 0
  locale: SG0018

File_AppendAllText:
  namespace: System.IO
  className: File
  member: method
  name: AppendAllText
  injectableArguments: 0
  locale: SG0018

File_AppendText:
  namespace: System.IO
  className: File
  member: method
  name: AppendText
  injectableArguments: 0
  locale: SG0018

File_Copy:
  namespace: System.IO
  className: File
  member: method
  name: Copy
  injectableArguments: 0,1
  locale: SG0018

File_Create:
  namespace: System.IO
  className: File
  member: method
  name: Create
  injectableArguments: 0
  locale: SG0018

File_Delete:
  namespace: System.IO
  className: File
  member: method
  name: Delete
  injectableArguments: 0
  locale: SG0018

#Open
File_Open:
  namespace: System.IO
  className: File
  member: method
  name: Open
  injectableArguments: 0
  locale: SG0018

File_OpenRead:
  namespace: System.IO
  className: File
  member: method
  name: OpenRead
  injectableArguments: 0
  locale: SG0018

File_OpenText:
  namespace: System.IO
  className: File
  member: method
  name: OpenText
  injectableArguments: 0
  locale: SG0018

File_OpenWrite:
  namespace: System.IO
  className: File
  member: method
  name: OpenWrite
  injectableArguments: 0
  locale: SG0018

#Read
File_ReadAllText:
  namespace: System.IO
  className: File
  member: method
  name: ReadAllText
  injectableArguments: 0
  locale: SG0018
  
File_ReadAllBytes:
  namespace: System.IO
  className: File
  member: method
  name: ReadAllBytes
  injectableArguments: 0
  locale: SG0018
  
File_ReadAllLines:
  namespace: System.IO
  className: File
  member: method
  name: ReadAllLines
  injectableArguments: 0
  locale: SG0018

File_ReadLines:
  namespace: System.IO
  className: File
  member: method
  name: ReadLines
  injectableArguments: 0
  locale: SG0018

File_Replace:
  namespace: System.IO
  className: File
  member: method
  name: Replace
  injectableArguments: 0,1
  locale: SG0018

#Write
File_WriteAllBytes:
  namespace: System.IO
  className: File
  member: method
  name: WriteAllBytes
  injectableArguments: 0
  locale: SG0018

File_WriteAllLines:
  namespace: System.IO
  className: File
  member: method
  name: WriteAllLines
  injectableArguments: 0
  locale: SG0018

File_WriteAllText:
  namespace: System.IO
  className: File
  member: method
  name: WriteAllText
  injectableArguments: 0
  locale: SG0018

#XmlReader

XmlReader_Create_uri:
  namespace: System.Xml
  className: XmlReader
  member: method
  name: Create
  argTypes: (System.String)
  injectableArguments: 0
  locale: SG0018

XmlReader_Create_uri_settings:
  namespace: System.Xml
  className: XmlReader
  member: method
  name: Create
  argTypes: (System.String, System.Xml.XmlReaderSettings)
  injectableArguments: 0
  locale: SG0018

XmlReader_Create_uri_settings_context:
  namespace: System.Xml
  className: XmlReader
  member: method
  name: Create
  argTypes: (System.String, System.Xml.XmlReaderSettings, System.Xml.XmlParserContext)
  injectableArguments: 0
  locale: SG0018

StreamReader_Create_path:
  namespace: System.IO
  className: StreamReader
  member: method
  name: .ctor
  argTypes: (System.String)
  injectableArguments: 0
  locale: SG0018

StreamReader_Create_path_bool:
  namespace: System.IO
  className: StreamReader
  member: method
  name: .ctor
  argTypes: (System.String, System.Boolean)
  injectableArguments: 0
  locale: SG0018

StreamReader_Create_path_encoding:
  namespace: System.IO
  className: StreamReader
  member: method
  name: .ctor
  argTypes: (System.String, System.Text.Encoding)
  injectableArguments: 0
  locale: SG0018

StreamReader_Create_path_encoding_bool:
  namespace: System.IO
  className: StreamReader
  member: method
  name: .ctor
  argTypes: (System.String, System.Text.Encoding, System.Boolean)
  injectableArguments: 0
  locale: SG0018

StreamReader_Create_path_encoding_bool_int:
  namespace: System.IO
  className: StreamReader
  member: method
  name: .ctor
  argTypes: (System.String, System.Text.Encoding, System.Boolean, System.Int32)
  injectableArguments: 0
  locale: SG0018
